//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalBpDm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyReports", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class MyReports : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalBpDm.ServiceReference1.MyReport[] allreportsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TerminalBpDm.ServiceReference1.MyReport[] allreports {
            get {
                return this.allreportsField;
            }
            set {
                if ((object.ReferenceEquals(this.allreportsField, value) != true)) {
                    this.allreportsField = value;
                    this.RaisePropertyChanged("allreports");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyReport", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class MyReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        private int korpusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string visitorField;
        
        private System.DateTime building_entering_datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invitorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFIdCardNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int korpus {
            get {
                return this.korpusField;
            }
            set {
                if ((this.korpusField.Equals(value) != true)) {
                    this.korpusField = value;
                    this.RaisePropertyChanged("korpus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string visitor {
            get {
                return this.visitorField;
            }
            set {
                if ((object.ReferenceEquals(this.visitorField, value) != true)) {
                    this.visitorField = value;
                    this.RaisePropertyChanged("visitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime building_entering_datetime {
            get {
                return this.building_entering_datetimeField;
            }
            set {
                if ((this.building_entering_datetimeField.Equals(value) != true)) {
                    this.building_entering_datetimeField = value;
                    this.RaisePropertyChanged("building_entering_datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string invitor {
            get {
                return this.invitorField;
            }
            set {
                if ((object.ReferenceEquals(this.invitorField, value) != true)) {
                    this.invitorField = value;
                    this.RaisePropertyChanged("invitor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string contacts {
            get {
                return this.contactsField;
            }
            set {
                if ((object.ReferenceEquals(this.contactsField, value) != true)) {
                    this.contactsField = value;
                    this.RaisePropertyChanged("contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RFIdCardNumber {
            get {
                return this.RFIdCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RFIdCardNumberField, value) != true)) {
                    this.RFIdCardNumberField = value;
                    this.RaisePropertyChanged("RFIdCardNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalBpDm.ServiceReference1.RequestPhoto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalBpDm.ServiceReference1.RequestRFID))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalBpDm.ServiceReference1.RequestCard))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalBpDm.ServiceReference1.RequestInfo RequestInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TerminalBpDm.ServiceReference1.RequestInfo RequestInfo {
            get {
                return this.RequestInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestInfoField, value) != true)) {
                    this.RequestInfoField = value;
                    this.RaisePropertyChanged("RequestInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestInfo", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class RequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalBpDm.ServiceReference1.Sender SenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TerminalBpDm.ServiceReference1.Sender Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestPhoto", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class RequestPhoto : TerminalBpDm.ServiceReference1.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalBpDm.ServiceReference1.RequestPhotoData RequestDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TerminalBpDm.ServiceReference1.RequestPhotoData RequestData {
            get {
                return this.RequestDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDataField, value) != true)) {
                    this.RequestDataField = value;
                    this.RaisePropertyChanged("RequestData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestRFID", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class RequestRFID : TerminalBpDm.ServiceReference1.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalBpDm.ServiceReference1.RequestRFIDData RequestDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TerminalBpDm.ServiceReference1.RequestRFIDData RequestData {
            get {
                return this.RequestDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDataField, value) != true)) {
                    this.RequestDataField = value;
                    this.RaisePropertyChanged("RequestData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestCard", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class RequestCard : TerminalBpDm.ServiceReference1.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalBpDm.ServiceReference1.RequestCardData RequestDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TerminalBpDm.ServiceReference1.RequestCardData RequestData {
            get {
                return this.RequestDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDataField, value) != true)) {
                    this.RequestDataField = value;
                    this.RaisePropertyChanged("RequestData");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestCardData", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class RequestCardData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sender", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class Sender : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestPhotoData", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class RequestPhotoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base64PhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardID {
            get {
                return this.CardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIDField, value) != true)) {
                    this.CardIDField = value;
                    this.RaisePropertyChanged("CardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Base64Photo {
            get {
                return this.Base64PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.Base64PhotoField, value) != true)) {
                    this.Base64PhotoField = value;
                    this.RaisePropertyChanged("Base64Photo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestRFIDData", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class RequestRFIDData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFID_NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardID {
            get {
                return this.CardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIDField, value) != true)) {
                    this.CardIDField = value;
                    this.RaisePropertyChanged("CardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RFID_Number {
            get {
                return this.RFID_NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RFID_NumberField, value) != true)) {
                    this.RFID_NumberField = value;
                    this.RaisePropertyChanged("RFID_Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalBpDm.ServiceReference1.ResponseCard))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIDField, value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCard", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class ResponseCard : TerminalBpDm.ServiceReference1.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvitersFullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvitersPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TerminalBpDm.ServiceReference1.Person[] ResponsiblePersonsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CabinetFloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CabinetNumberField;
        
        private bool NeedPhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisitorFullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base64PhotoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardID {
            get {
                return this.CardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIDField, value) != true)) {
                    this.CardIDField = value;
                    this.RaisePropertyChanged("CardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string InvitersFullname {
            get {
                return this.InvitersFullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.InvitersFullnameField, value) != true)) {
                    this.InvitersFullnameField = value;
                    this.RaisePropertyChanged("InvitersFullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string InvitersPhoneNumber {
            get {
                return this.InvitersPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvitersPhoneNumberField, value) != true)) {
                    this.InvitersPhoneNumberField = value;
                    this.RaisePropertyChanged("InvitersPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TerminalBpDm.ServiceReference1.Person[] ResponsiblePersons {
            get {
                return this.ResponsiblePersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsiblePersonsField, value) != true)) {
                    this.ResponsiblePersonsField = value;
                    this.RaisePropertyChanged("ResponsiblePersons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CabinetFloor {
            get {
                return this.CabinetFloorField;
            }
            set {
                if ((object.ReferenceEquals(this.CabinetFloorField, value) != true)) {
                    this.CabinetFloorField = value;
                    this.RaisePropertyChanged("CabinetFloor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CabinetNumber {
            get {
                return this.CabinetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CabinetNumberField, value) != true)) {
                    this.CabinetNumberField = value;
                    this.RaisePropertyChanged("CabinetNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool NeedPhoto {
            get {
                return this.NeedPhotoField;
            }
            set {
                if ((this.NeedPhotoField.Equals(value) != true)) {
                    this.NeedPhotoField = value;
                    this.RaisePropertyChanged("NeedPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string VisitorFullname {
            get {
                return this.VisitorFullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.VisitorFullnameField, value) != true)) {
                    this.VisitorFullnameField = value;
                    this.RaisePropertyChanged("VisitorFullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Base64Photo {
            get {
                return this.Base64PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.Base64PhotoField, value) != true)) {
                    this.Base64PhotoField = value;
                    this.RaisePropertyChanged("Base64Photo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://192.168.7.23/Services/TerminalService")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService", ConfigurationName="ServiceReference1.TerminalService1Soap")]
    public interface TerminalService1Soap {
        
        // CODEGEN: Generating message contract since element name GetReportResult from namespace http://192.168.7.23/Services/TerminalService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/GetReport", ReplyAction="*")]
        TerminalBpDm.ServiceReference1.GetReportResponse GetReport(TerminalBpDm.ServiceReference1.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/GetReport", ReplyAction="*")]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.GetReportResponse> GetReportAsync(TerminalBpDm.ServiceReference1.GetReportRequest request);
        
        // CODEGEN: Generating message contract since element name Request from namespace http://192.168.7.23/Services/TerminalService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/GetVisitor", ReplyAction="*")]
        TerminalBpDm.ServiceReference1.GetVisitorResponse GetVisitor(TerminalBpDm.ServiceReference1.GetVisitorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/GetVisitor", ReplyAction="*")]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.GetVisitorResponse> GetVisitorAsync(TerminalBpDm.ServiceReference1.GetVisitorRequest request);
        
        // CODEGEN: Generating message contract since element name Request from namespace http://192.168.7.23/Services/TerminalService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/SetVisitorsPhoto", ReplyAction="*")]
        TerminalBpDm.ServiceReference1.SetVisitorsPhotoResponse SetVisitorsPhoto(TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/SetVisitorsPhoto", ReplyAction="*")]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.SetVisitorsPhotoResponse> SetVisitorsPhotoAsync(TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequest request);
        
        // CODEGEN: Generating message contract since element name Request from namespace http://192.168.7.23/Services/TerminalService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/SetVisitorsRFID", ReplyAction="*")]
        TerminalBpDm.ServiceReference1.SetVisitorsRFIDResponse SetVisitorsRFID(TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/SetVisitorsRFID", ReplyAction="*")]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.SetVisitorsRFIDResponse> SetVisitorsRFIDAsync(TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequest request);
        
        // CODEGEN: Generating message contract since element name Request from namespace http://192.168.7.23/Services/TerminalService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/CardsEnded", ReplyAction="*")]
        TerminalBpDm.ServiceReference1.CardsEndedResponse CardsEnded(TerminalBpDm.ServiceReference1.CardsEndedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.7.23/Services/TerminalService/CardsEnded", ReplyAction="*")]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.CardsEndedResponse> CardsEndedAsync(TerminalBpDm.ServiceReference1.CardsEndedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReport", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.GetReportRequestBody Body;
        
        public GetReportRequest() {
        }
        
        public GetReportRequest(TerminalBpDm.ServiceReference1.GetReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetReportRequestBody {
        
        public GetReportRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportResponse", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.GetReportResponseBody Body;
        
        public GetReportResponse() {
        }
        
        public GetReportResponse(TerminalBpDm.ServiceReference1.GetReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class GetReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.MyReports GetReportResult;
        
        public GetReportResponseBody() {
        }
        
        public GetReportResponseBody(TerminalBpDm.ServiceReference1.MyReports GetReportResult) {
            this.GetReportResult = GetReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVisitorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVisitor", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.GetVisitorRequestBody Body;
        
        public GetVisitorRequest() {
        }
        
        public GetVisitorRequest(TerminalBpDm.ServiceReference1.GetVisitorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class GetVisitorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.RequestCard Request;
        
        public GetVisitorRequestBody() {
        }
        
        public GetVisitorRequestBody(TerminalBpDm.ServiceReference1.RequestCard Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVisitorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVisitorResponse", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.GetVisitorResponseBody Body;
        
        public GetVisitorResponse() {
        }
        
        public GetVisitorResponse(TerminalBpDm.ServiceReference1.GetVisitorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class GetVisitorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.ResponseCard GetVisitorResult;
        
        public GetVisitorResponseBody() {
        }
        
        public GetVisitorResponseBody(TerminalBpDm.ServiceReference1.ResponseCard GetVisitorResult) {
            this.GetVisitorResult = GetVisitorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetVisitorsPhotoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetVisitorsPhoto", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequestBody Body;
        
        public SetVisitorsPhotoRequest() {
        }
        
        public SetVisitorsPhotoRequest(TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class SetVisitorsPhotoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.RequestPhoto Request;
        
        public SetVisitorsPhotoRequestBody() {
        }
        
        public SetVisitorsPhotoRequestBody(TerminalBpDm.ServiceReference1.RequestPhoto Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetVisitorsPhotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetVisitorsPhotoResponse", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.SetVisitorsPhotoResponseBody Body;
        
        public SetVisitorsPhotoResponse() {
        }
        
        public SetVisitorsPhotoResponse(TerminalBpDm.ServiceReference1.SetVisitorsPhotoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class SetVisitorsPhotoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.Response SetVisitorsPhotoResult;
        
        public SetVisitorsPhotoResponseBody() {
        }
        
        public SetVisitorsPhotoResponseBody(TerminalBpDm.ServiceReference1.Response SetVisitorsPhotoResult) {
            this.SetVisitorsPhotoResult = SetVisitorsPhotoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetVisitorsRFIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetVisitorsRFID", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequestBody Body;
        
        public SetVisitorsRFIDRequest() {
        }
        
        public SetVisitorsRFIDRequest(TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class SetVisitorsRFIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.RequestRFID Request;
        
        public SetVisitorsRFIDRequestBody() {
        }
        
        public SetVisitorsRFIDRequestBody(TerminalBpDm.ServiceReference1.RequestRFID Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetVisitorsRFIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetVisitorsRFIDResponse", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.SetVisitorsRFIDResponseBody Body;
        
        public SetVisitorsRFIDResponse() {
        }
        
        public SetVisitorsRFIDResponse(TerminalBpDm.ServiceReference1.SetVisitorsRFIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class SetVisitorsRFIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.Response SetVisitorsRFIDResult;
        
        public SetVisitorsRFIDResponseBody() {
        }
        
        public SetVisitorsRFIDResponseBody(TerminalBpDm.ServiceReference1.Response SetVisitorsRFIDResult) {
            this.SetVisitorsRFIDResult = SetVisitorsRFIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CardsEndedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CardsEnded", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.CardsEndedRequestBody Body;
        
        public CardsEndedRequest() {
        }
        
        public CardsEndedRequest(TerminalBpDm.ServiceReference1.CardsEndedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class CardsEndedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.Request Request;
        
        public CardsEndedRequestBody() {
        }
        
        public CardsEndedRequestBody(TerminalBpDm.ServiceReference1.Request Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CardsEndedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CardsEndedResponse", Namespace="http://192.168.7.23/Services/TerminalService", Order=0)]
        public TerminalBpDm.ServiceReference1.CardsEndedResponseBody Body;
        
        public CardsEndedResponse() {
        }
        
        public CardsEndedResponse(TerminalBpDm.ServiceReference1.CardsEndedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://192.168.7.23/Services/TerminalService")]
    public partial class CardsEndedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalBpDm.ServiceReference1.Response CardsEndedResult;
        
        public CardsEndedResponseBody() {
        }
        
        public CardsEndedResponseBody(TerminalBpDm.ServiceReference1.Response CardsEndedResult) {
            this.CardsEndedResult = CardsEndedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TerminalService1SoapChannel : TerminalBpDm.ServiceReference1.TerminalService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalService1SoapClient : System.ServiceModel.ClientBase<TerminalBpDm.ServiceReference1.TerminalService1Soap>, TerminalBpDm.ServiceReference1.TerminalService1Soap {
        
        public TerminalService1SoapClient() {
        }
        
        public TerminalService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalBpDm.ServiceReference1.GetReportResponse TerminalBpDm.ServiceReference1.TerminalService1Soap.GetReport(TerminalBpDm.ServiceReference1.GetReportRequest request) {
            return base.Channel.GetReport(request);
        }
        
        public TerminalBpDm.ServiceReference1.MyReports GetReport() {
            TerminalBpDm.ServiceReference1.GetReportRequest inValue = new TerminalBpDm.ServiceReference1.GetReportRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.GetReportRequestBody();
            TerminalBpDm.ServiceReference1.GetReportResponse retVal = ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).GetReport(inValue);
            return retVal.Body.GetReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.GetReportResponse> TerminalBpDm.ServiceReference1.TerminalService1Soap.GetReportAsync(TerminalBpDm.ServiceReference1.GetReportRequest request) {
            return base.Channel.GetReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.GetReportResponse> GetReportAsync() {
            TerminalBpDm.ServiceReference1.GetReportRequest inValue = new TerminalBpDm.ServiceReference1.GetReportRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.GetReportRequestBody();
            return ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).GetReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalBpDm.ServiceReference1.GetVisitorResponse TerminalBpDm.ServiceReference1.TerminalService1Soap.GetVisitor(TerminalBpDm.ServiceReference1.GetVisitorRequest request) {
            return base.Channel.GetVisitor(request);
        }
        
        public TerminalBpDm.ServiceReference1.ResponseCard GetVisitor(TerminalBpDm.ServiceReference1.RequestCard Request) {
            TerminalBpDm.ServiceReference1.GetVisitorRequest inValue = new TerminalBpDm.ServiceReference1.GetVisitorRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.GetVisitorRequestBody();
            inValue.Body.Request = Request;
            TerminalBpDm.ServiceReference1.GetVisitorResponse retVal = ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).GetVisitor(inValue);
            return retVal.Body.GetVisitorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.GetVisitorResponse> TerminalBpDm.ServiceReference1.TerminalService1Soap.GetVisitorAsync(TerminalBpDm.ServiceReference1.GetVisitorRequest request) {
            return base.Channel.GetVisitorAsync(request);
        }
        
        public System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.GetVisitorResponse> GetVisitorAsync(TerminalBpDm.ServiceReference1.RequestCard Request) {
            TerminalBpDm.ServiceReference1.GetVisitorRequest inValue = new TerminalBpDm.ServiceReference1.GetVisitorRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.GetVisitorRequestBody();
            inValue.Body.Request = Request;
            return ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).GetVisitorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalBpDm.ServiceReference1.SetVisitorsPhotoResponse TerminalBpDm.ServiceReference1.TerminalService1Soap.SetVisitorsPhoto(TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequest request) {
            return base.Channel.SetVisitorsPhoto(request);
        }
        
        public TerminalBpDm.ServiceReference1.Response SetVisitorsPhoto(TerminalBpDm.ServiceReference1.RequestPhoto Request) {
            TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequest inValue = new TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequestBody();
            inValue.Body.Request = Request;
            TerminalBpDm.ServiceReference1.SetVisitorsPhotoResponse retVal = ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).SetVisitorsPhoto(inValue);
            return retVal.Body.SetVisitorsPhotoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.SetVisitorsPhotoResponse> TerminalBpDm.ServiceReference1.TerminalService1Soap.SetVisitorsPhotoAsync(TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequest request) {
            return base.Channel.SetVisitorsPhotoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.SetVisitorsPhotoResponse> SetVisitorsPhotoAsync(TerminalBpDm.ServiceReference1.RequestPhoto Request) {
            TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequest inValue = new TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.SetVisitorsPhotoRequestBody();
            inValue.Body.Request = Request;
            return ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).SetVisitorsPhotoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalBpDm.ServiceReference1.SetVisitorsRFIDResponse TerminalBpDm.ServiceReference1.TerminalService1Soap.SetVisitorsRFID(TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequest request) {
            return base.Channel.SetVisitorsRFID(request);
        }
        
        public TerminalBpDm.ServiceReference1.Response SetVisitorsRFID(TerminalBpDm.ServiceReference1.RequestRFID Request) {
            TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequest inValue = new TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequestBody();
            inValue.Body.Request = Request;
            TerminalBpDm.ServiceReference1.SetVisitorsRFIDResponse retVal = ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).SetVisitorsRFID(inValue);
            return retVal.Body.SetVisitorsRFIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.SetVisitorsRFIDResponse> TerminalBpDm.ServiceReference1.TerminalService1Soap.SetVisitorsRFIDAsync(TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequest request) {
            return base.Channel.SetVisitorsRFIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.SetVisitorsRFIDResponse> SetVisitorsRFIDAsync(TerminalBpDm.ServiceReference1.RequestRFID Request) {
            TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequest inValue = new TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.SetVisitorsRFIDRequestBody();
            inValue.Body.Request = Request;
            return ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).SetVisitorsRFIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalBpDm.ServiceReference1.CardsEndedResponse TerminalBpDm.ServiceReference1.TerminalService1Soap.CardsEnded(TerminalBpDm.ServiceReference1.CardsEndedRequest request) {
            return base.Channel.CardsEnded(request);
        }
        
        public TerminalBpDm.ServiceReference1.Response CardsEnded(TerminalBpDm.ServiceReference1.Request Request) {
            TerminalBpDm.ServiceReference1.CardsEndedRequest inValue = new TerminalBpDm.ServiceReference1.CardsEndedRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.CardsEndedRequestBody();
            inValue.Body.Request = Request;
            TerminalBpDm.ServiceReference1.CardsEndedResponse retVal = ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).CardsEnded(inValue);
            return retVal.Body.CardsEndedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.CardsEndedResponse> TerminalBpDm.ServiceReference1.TerminalService1Soap.CardsEndedAsync(TerminalBpDm.ServiceReference1.CardsEndedRequest request) {
            return base.Channel.CardsEndedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TerminalBpDm.ServiceReference1.CardsEndedResponse> CardsEndedAsync(TerminalBpDm.ServiceReference1.Request Request) {
            TerminalBpDm.ServiceReference1.CardsEndedRequest inValue = new TerminalBpDm.ServiceReference1.CardsEndedRequest();
            inValue.Body = new TerminalBpDm.ServiceReference1.CardsEndedRequestBody();
            inValue.Body.Request = Request;
            return ((TerminalBpDm.ServiceReference1.TerminalService1Soap)(this)).CardsEndedAsync(inValue);
        }
    }
}
